### ISSUE TITLE
No longer matches CC textures, please update

### ISSUE THREAD

**Issue by Merith-TK** [3prm3/cc-pack#1]

**Comment by nullified33** [comment]
Please elaborate.

**Comment by Merith-TK** [comment]
Interface UI textures have been updated in CC:T and CC:R to accomodate two buttons on the left side, a power button and a "terminate" button, 

currently your textures do not accomodate these new buttons

**Comment by nullified33** [comment]
Ok, will fix tomorrow.

**Comment by nullified33** [comment]
Updated textures.
